### ISSUE TITLE
pip install does not work?

### ISSUE THREAD

**Issue by olenz** [baojie/smw#1]
Hi!

First of all: this looks very promising!

I had no problems to install smw directly from the sources, nor when using 

```
pip install git+git://github.com/baojie/smw.git
```

However, when just using pip, this is what happens. It looks as though the pip package does not contain README.md:

```
> pip install smw
Downloading/unpacking smw
  Downloading smw-0.1.2.tar.gz
  Running setup.py egg_info for package smw
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_olenz/smw/setup.py", line 24, in <module>
        long_description=open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_olenz/smw/setup.py", line 24, in <module>

    long_description=open('README.md').read(),

IOError: [Errno 2] No such file or directory: 'README.md'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_olenz/smw
Storing complete log in /home/olenz/.pip/pip.log
```

Cheers!

  Olaf

**Comment by baojie** [comment]
Hi Olaf

I uploaded a hotfix version 0.1.2.1 https://github.com/baojie/smw/commit/e7fe57719d1eb89a89009dd9557c2e3ddc38b471

please try
 pip install smw==0.1.2.1

**Comment by olenz** [comment]
Yes, it works now. Excellent!
