### ISSUE TITLE
pip install smw error

### ISSUE THREAD

**Issue by MitchBarnett** [baojie/smw#3]
running `pip install smw` and `pip install git+git://github.com/baojie/smw.git`
gives the error `Command "python setup.py egg_info" failed with error code 1 in C:\Users\Username\AppData\Local\Temp\pip-install-xnl5se48\enum\`

full log:

```
C:\WINDOWS\system32>pip install git+git://github.com/baojie/smw.git
Collecting git+git://github.com/baojie/smw.git
  Cloning git://github.com/baojie/smw.git to c:\users\username\appdata\local\temp\pip-req-build-2clo57zu
Requirement already satisfied: mwclient>=0.7dev in c:\users\username\appdata\local\programs\python\python37-32\lib\site-packages (from smw==0.1.3.3) (0.9.3)
Collecting rdflib (from smw==0.1.3.3)
  Using cached https://files.pythonhosted.org/packages/3c/fe/630bacb652680f6d481b9febbb3e2c3869194a1a5fc3401a4a41195a2f8f/rdflib-4.2.2-py3-none-any.whl
Collecting beautifulsoup4 (from smw==0.1.3.3)
  Using cached https://files.pythonhosted.org/packages/1d/5d/3260694a59df0ec52f8b4883f5d23b130bc237602a1411fa670eae12351e/beautifulsoup4-4.7.1-py3-none-any.whl
Collecting enum (from smw==0.1.3.3)
  Using cached https://files.pythonhosted.org/packages/02/a0/32e1d5a21b703f600183e205aafc6773577e16429af5ad3c3f9b956b07ca/enum-0.4.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\site-packages\setuptools\__init__.py", line 6, in <module>
        import distutils.core
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\distutils\dist.py", line 9, in <module>
        import re
      File "c:\users\username\appdata\local\programs\python\python37-32\lib\re.py", line 143, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Username\AppData\Local\Temp\pip-install-xnl5se48\enum\

```

**Comment by Kugeleis** [comment]
same here, any solution out there?
